name: git workshop
on:
  release:
    types: [published]

jobs:
  full workshop flow:
    runs-on: ubuntu-latest
    steps:
    - name: checkout tag
      uses: actions/checkout@v3
      with:
        ref: ${{github.ref_name}}

